### ISSUE TITLE
Undefined array key "no_quotes

### ISSUE THREAD

**Issue by staabm** [xsist10/cadfael#66]
after I got the tool working with the Fix from https://github.com/xsist10/cadfael/pull/65

I am now running into more errors

```
PHP Warning:  Undefined array key "no_quotes" in C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\src\Engine\Entity\Query.php on line 138
PHP Warning:  Trying to access array offset on value of type null in C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\src\Engine\Entity\Query.php on line 138
PHP Fatal error:  Uncaught TypeError: array_pop(): Argument #1 ($array) must be of type array, null given in C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\src\Engine\Entity\Query.php:140
Stack trace:
#0 C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\src\Engine\Entity\Query.php(140): array_pop()
#1 C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\src\Engine\Entity\Query.php(110): Cadfael\Engine\Entity\Query->getTableNamesInQuery()
#2 C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\src\Engine\Factory.php(155): Cadfael\Engine\Entity\Query->linkTablesToQuery()
#3 C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\src\Engine\Factory.php(727): Cadfael\Engine\Factory->getEventStatementsSummary()
#4 C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\src\Cli\Command\RunCommand.php(145): Cadfael\Engine\Factory->buildDatabase()
#5 C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\src\Cli\Command\RunCommand.php(271): Cadfael\Cli\Command\RunCommand->runChecksAgainstSchema()
#6 C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\src\Cli\Command\RunCommand.php(298): Cadfael\Cli\Command\RunCommand->processSchemas()
#7 C:\dvl\Workspace\cadfael\vendor\symfony\console\Command\Command.php(298): Cadfael\Cli\Command\RunCommand->execute()
#8 C:\dvl\Workspace\cadfael\vendor\symfony\console\Application.php(1028): Symfony\Component\Console\Command\Command->run()
#9 C:\dvl\Workspace\cadfael\vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#10 C:\dvl\Workspace\cadfael\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun()
#11 C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\bin\cadfael(19): Symfony\Component\Console\Application->run()
#12 C:\dvl\Workspace\cadfael\vendor\bin\cadfael(120): include('...')
#13 {main}
  thrown in C:\dvl\Workspace\cadfael\vendor\cadfael\cadfael\src\Engine\Entity\Query.php on line 140

```

I think cadfael is trying to parse a sql statement - which it somehow found in the server.

tested on https://github.com/xsist10/cadfael/commit/eda93c351525c63ec98386dd2914555b2ecf3a4f

**Comment by staabm** [comment]
I guess the used PHPParser has problems to parse a query like

`SELECT a FROM table INNER JOIN (SELECT b from table2)`

**Comment by staabm** [comment]
I think another problematic query is

```
SELECT
    a,
    b
FROM
    (
        `shop`
    JOIN table2 ON((table2.x = shop.y))
    ) 
```

**Comment by xsist10** [comment]
So Cadfael uses [`greenlion/php-sql-parser`](https://github.com/greenlion/PHP-SQL-Parser) to parse queries from the `performance_schema.events_statements_summary_by_digest` to try detect inefficient queries or badly designed functions in the WHERE statement that prevent index usage.

On review of the code I see it only runs the checks if you include `--performance_schema` in your run parameters but it attempts to load and parse the data regardless so that's something to improve.

So this needs three fixes:
1. Don't load `performance_schema` data unless the `--performance_schema` is passed.
2. Attempt to find out why the `greenlion/php-sql-parser` is dying on these queries.
3. Ensure that the code doesn't die if the query parsing fails and returns a relevant warning to the user.

**Comment by xsist10** [comment]
This issue should now be resolved in the latest release - https://github.com/xsist10/cadfael/releases/tag/0.2.5

Please give it a try and let me know if I can close this issue.

**Comment by xsist10** [comment]
@staabm ping about this issue.

**Comment by xsist10** [comment]
No problem. You're doing me a favour and trying the tool out in different environments and, most importantly, spending your time reporting issues.
