### ISSUE TITLE
filter issues by status

### ISSUE THREAD

**Issue by staabm** [xsist10/cadfael#79]
running `php vendor/bin/cadfael run --host mysql80.ab --username testuser --port 3306 mydb -vvv` yields a big wall of text.
its kind of overwhelming and identifying what is critical or needs attention first is hard to grasp for the user.

it would be great if I could filter to only show `Critical`, `Warning`,.. etc.
when filtered there could be a summary table on the bottom which shows me how much errors/warnings/.. I did not see, because of my current filter

**Comment by xsist10** [comment]
Similar to the issue #41. I'll pick this one up next.
