### ISSUE TITLE
More Account Reports

### ISSUE THREAD

**Issue by isotopp** [xsist10/cadfael#85]
Cadfael should do more reporting on accounts:

- Accounts that use (for the server version outdated) authentication methods.
  - 5.6 should alert on `mysql_old_password`, 8.0 on `mysql_native_password`.
- Locked and expired accounts should be reported.

- Accounts with excessive privileges should be reported
  - Accounts with SUPER/rootlike/global privs.
  - Accounts that can execute DDL.

**Comment by xsist10** [comment]
This will be broken down into 3 checks:

- [ ] Account with outdated authentication methods
- [ ] Locked or expired accounts
- [ ] Accounts with excessive permissions

For the last check, what would be the condition for warning? I suspect there will always be at least one account with DDL permissions and at least one SUPER user time account in normal operations. Or just make it always warn but not at a high warning level (just a `CONCERN` versus a `CRITICAL` issue)?

**Comment by xsist10** [comment]
Hey @isotopp. Are you still interested in the last set of checks "Accounts with excessive permissions"? If so I'd love your input on how best to structure it (see https://github.com/xsist10/cadfael/issues/85#issuecomment-1372809134).

If not I'll close up this issues with the other two checks since implemented.

**Comment by isotopp** [comment]
https://www.percona.com/blog/a-quick-peek-at-mysql-8-0-34-and-mysql-8-1-0/

> .1.0 is based on 8.0.34, so along with the above changes, you get some additional material. The mysql_native_password authentication plugin is deprecated and subject to removal in a future version of MySQL.
